In [ ]:
import numpy as np
import pandas as pd

In [3]:
import pandas as pd
data = {
   'Name': ['John', 'Anna', 'Peter', 'Linda'],
   'Age': [28, 34, 29, 42],
   'City': ['New York', 'Paris', 'Berlin', 'London'],
   'Salary': [65000, 70000, 62000, 85000]
}
a = pd.DataFrame(data)
a

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#selection and indexing of columns
a['Name'] #indexing selection

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [8]:
a[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [9]:
#creating a new columns

a["dept"] =["cse","finance","hr","cse"]
a

    Name  Age      City  Salary     dept
0   John   28  New York   65000      cse
1   Anna   34     Paris   70000  finance
2  Peter   29    Berlin   62000       hr
3  Linda   42    London   85000      cse

In [ ]:
#remove columns
a.drop("dept",axis=1) #column will removed but not from original array

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
a.drop("dept", axis=1, inplace=True) #remove column from original array

In [18]:
a

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
#for removing rows axis = 0

In [ ]:
#selecting rows

a.loc[0] #location
a.loc[[0,1]]
a.iloc[3] #index location

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [23]:
#selecting subsets of rows and columns
a.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [25]:
#conditional selection
#if i want to see whose age is greater than 30

a[a["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [26]:
#and must be a native of paris
a[(a["Age"]>30) & (a["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000