In [2]:
import numpy as np
import pandas as pd
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [3]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
#finding missing data
df.isna() #bata dega kon kon si value null hai

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
df.isna().sum() #bata dega kis column me kitni value null hai

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df.isna().any() #bata dega ki column koi null value exist karti hai ya nhi

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
#removing missing data
df.dropna() #row jisme null value nhi hai

     A  B    C    D
0  1.0  1  1.0  1.0

In [8]:
df.dropna(thresh=3) #row jisme atleast 3 value null h

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
#Filling the missing data
df.fillna(0) #jitni bhi null value hogi usme null bharjaega

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values = {'A':100,'B':20,'C':40,'D':200}
df.fillna(value=values) #null value ko kuch values dena

       A  B     C      D
0    1.0  1   1.0    1.0
1    2.0  2   2.0  200.0
2  100.0  3   3.0  200.0
3    4.0  4  40.0  200.0
4    5.0  5  40.0    5.0

In [11]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0