operations

In [2]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [3]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [4]:
df1.shape

(5, 3)

In [5]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [6]:
df1.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [ ]:
df1.describe() #saare aggregate functions batadega

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [8]:
#broadcasting
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [9]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
#dataframes applying functions
def square(x):
    return x**2
df1['A'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64

In [12]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [13]:
df1['A'] = df1['A'].apply(square)

In [14]:
df1

    A   B    C
0   1  10  100
1   4  20  200
2   9  30  300
3  16  40  400
4  25  50  500

In [15]:
df1['B'] = df1['B'].apply(lambda x:x**2)

In [16]:
df1

    A     B    C
0   1   100  100
1   4   400  200
2   9   900  300
3  16  1600  400
4  25  2500  500