In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
lst = [1,2,3]
arr = np.array([10,20,30])
dict = {
    1:10,
    2:20,
    3:30
}

In [7]:
pd.Series(lst)

0    1
1    2
2    3
dtype: int64

In [8]:
pd.Series(arr , index = labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64